spring:
  datasource:
    url: jdbc:sqlserver://mssqlstud.fhict.local:1433;databaseName=dbi550619_semester3;encrypt=true;trustServerCertificate=true
    username: dbi550619_semester3
    password: SMWsmwsmw12%
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: validate # use 'update' only if you want Hibernate to change tables
    properties:
      hibernate.dialect: org.hibernate.dialect.SQLServerDialect
      hibernate.format_sql: true
      hibernate.default_schema: dbo
    open-in-view: false
  # Keep exact table/column names as in SQL Server (Users, Budgets, etc.)
  jpa.hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server:
  port: 8081
