server:
  port: 8081
spring:
  sql:
    init:
      mode: always
      schema-locations: classpath:schema-h2.sql

  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:file:./data/pfdb;MODE=MSSQLServer;DATABASE_TO_UPPER=false
    username: magwit
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        default_schema: dbo
