-- Personal Finance Tracker — Core H2 schema (Users, Accounts, Categories, Transactions)
-- Save as: src/main/resources/schema-h2.sql

CREATE SCHEMA IF NOT EXISTS dbo;

-- users
CREATE TABLE IF NOT EXISTS dbo.users(
  user_id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username      VARCHAR(100)  NOT NULL UNIQUE,
  password_hash VARCHAR(60) NOT NULL, -- BCrypt hash
  created_at    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- accounts
CREATE TABLE IF NOT EXISTS dbo.accounts(
  account_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    INT            NOT NULL,
  name       VARCHAR(100)   NOT NULL,
  type       VARCHAR(50)    NOT NULL,   -- Cash/Bank/Credit/Investment
  currency   CHAR(3)        NOT NULL DEFAULT 'EUR',
  balance    DECIMAL(18,2)  NOT NULL DEFAULT 0,
  created_at TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_accounts_user FOREIGN KEY (user_id)
    REFERENCES dbo.users(user_id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_accounts_user_name ON dbo.accounts(user_id, name);

-- categories
CREATE TABLE IF NOT EXISTS dbo.categories(
  category_id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id            INT           NOT NULL,
  name               VARCHAR(100)  NOT NULL,
  type               CHAR(1)       NOT NULL,  -- 'I' income, 'E' expense
  parent_category_id INT           NULL,
  created_at         TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_categories_user   FOREIGN KEY (user_id)
    REFERENCES dbo.users(user_id) ON DELETE CASCADE,
  CONSTRAINT fk_categories_parent FOREIGN KEY (parent_category_id)
    REFERENCES dbo.categories(category_id),
  CONSTRAINT ck_categories_type CHECK (type IN ('I','E'))
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_categories_user_name ON dbo.categories(user_id, name);

-- transactions
CREATE TABLE IF NOT EXISTS dbo.transactions(
  transaction_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id        INT            NOT NULL,
  account_id     INT            NOT NULL,
  category_id    INT            NULL,
  amount         DECIMAL(18,2)  NOT NULL,    -- + income, - expense
  txn_date       DATE           NOT NULL,
  description    VARCHAR(500)   NULL,
  created_at     TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_tx_user     FOREIGN KEY (user_id)     REFERENCES dbo.users(user_id)       ON DELETE CASCADE,
  CONSTRAINT fk_tx_account  FOREIGN KEY (account_id)  REFERENCES dbo.accounts(account_id) ON DELETE CASCADE,
  CONSTRAINT fk_tx_category FOREIGN KEY (category_id) REFERENCES dbo.categories(category_id)
);
CREATE INDEX IF NOT EXISTS ix_tx_user_date    ON dbo.transactions(user_id, txn_date);
CREATE INDEX IF NOT EXISTS ix_tx_account_date ON dbo.transactions(account_id, txn_date);
CREATE INDEX IF NOT EXISTS ix_tx_category     ON dbo.transactions(category_id);
